name: sa_base
description: A new Flutter project.
# The following line prevents the package from being accidentally published to

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.19.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_flavorizr: ^2.1.5
  injectable: ^2.1.0
  get_it: ^7.2.0
  shared_preferences: ^2.0.18
  retrofit: ^4.0.1
  logger: any
  dio: ^5.0.1
  freezed_annotation: ^2.2.0
  json_annotation: ^4.8.0
  dartz: ^0.10.1
  flutter_bloc: ^8.1.2
  equatable: ^2.0.5
  bloc_concurrency: ^0.2.1
  stream_transform: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  injectable_generator: ^2.1.4
  build_runner: ^2.3.3
  retrofit_generator: ^5.0.0
  json_serializable: ^6.6.1
  freezed: ^2.3.2

flutter:


  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages

flavorizr:
  flavors:
    a:
      app:
        name: "App A"

      android:
        applicationId: "com.sotatek.a"
        icon: "assets/images/A.png"

      ios:
        bundleId: "com.sotatek.a"
        icon: "assets/images/A.png"

    b:
      app:
        name: "App B"

      android:
        applicationId: "com.sotatek.b"
        icon: "assets/images/B.png"

      ios:
        bundleId: "com.sotatek.b"
        icon: "assets/images/B.png"

    c:
      app:
        name: "App C"

      android:
        applicationId: "com.sotatek.c"
        icon: "assets/images/C.png"

      ios:
        bundleId: "com.sotatek.c"
        icon: "assets/images/C.png"

#  instructions:
#    - assets:download
#    - assets:extract
#    - assets:clean
#    - android:buildGradle
#    - android:androidManifest
##    - android:dummyAssets
#    - android:icons
#    - flutter:flavors
##    - flutter:app
#    - flutter:pages
#    - flutter:targets
#    - google:firebase
##    - huawei:agconnect
#    - ide:config
#    - ios:xcconfig
#    - ios:buildTargets
#    - ios:schema
##    - ios:dummyAssets
#    - ios:icons
#    - ios:plist
#    - ios:launchScreen